-- Mentis Arena V3.2 Questions Seed
-- Clear old questions
DELETE FROM arena_questions;

INSERT INTO arena_questions (category, question_text, options, correct_option, difficulty) VALUES
-- FELSEFE LİGİ
('Felsefe Ligi', 'Kim "Düşünüyorum, öyleyse varım" (Cogito, ergo sum) demiştir?', '["Immanuel Kant", "Rene Descartes", "Sokrates", "Friedrich Nietzsche"]', 1, 'easy'),
('Felsefe Ligi', 'Hangisi Stoacılık felsefesinin önemli temsilcilerinden biridir?', '["Marcus Aurelius", "Karl Marx", "Jean-Paul Sartre", "Platon"]', 0, 'medium'),
('Felsefe Ligi', 'Mağara Alegorisi hangi filozofa aittir?', '["Aristoteles", "Epiküros", "Platon", "Herakleitos"]', 2, 'easy'),
('Felsefe Ligi', 'Üstinsan (Übermensch) kavramını ortaya atan filozof kimdir?', '["Arthur Schopenhauer", "Friedrich Nietzsche", "Hegel", "Kant"]', 1, 'medium'),
('Felsefe Ligi', '"Aynı nehirde iki kez yıkanılmaz" sözü kime aittir?', '["Herakleitos", "Parmenides", "Thales", "Anaksimandros"]', 0, 'medium'),
('Felsefe Ligi', 'Devlet adlı eserinde "Filozof Kral" fikrini savunan düşünür kimdir?', '["Aristoteles", "Sokrates", "Machiavelli", "Platon"]', 3, 'easy'),
('Felsefe Ligi', 'Varoluşçuluğun (Existentialism) temel ilkesi nedir?', '["Öz, varoluştan önce gelir", "Varoluş, özden önce gelir", "Her şey önceden belirlenmiştir", "Madde tek gerçektir"]', 1, 'hard'),
('Felsefe Ligi', 'Tabula Rasa (Boş Levha) kavramıyla bilinen İngiliz filozof kimdir?', '["John Locke", "Thomas Hobbes", "David Hume", "George Berkeley"]', 0, 'medium'),
('Felsefe Ligi', 'Diyalektik materyalizm kavramını felsefeye kimler kazandırmıştır?', '["Sartre & Camus", "Marx & Engels", "Kant & Hegel", "Deleuze & Guattari"]', 1, 'hard'),
('Felsefe Ligi', 'Hangisi Sokrates''in savunmasında geçen ünlü sözlerinden biridir?', '["Bilgi güçtür", "Sorgulanmamış hayat yaşanmaya değmez", "Tanrı öldü", "Cehennem başkalarıdır"]', 1, 'medium'),
('Felsefe Ligi', 'Pragmatizm (Faydacılık) felsefesinin kurucularından olan Amerikalı düşünür kimdir?', '["William James", "John Stuart Mill", "Jeremy Bentham", "Bertrand Russell"]', 0, 'hard'),
('Felsefe Ligi', 'Kategorik İmperatif (Kesin Buyruk) ahlak anlayışı kime aittir?', '["Spinoza", "Kant", "Kierkegaard", "Heidegger"]', 1, 'hard'),
('Felsefe Ligi', 'Panoptikon kavramını modern iktidar analizinde kullanan Fransız filozof kimdir?', '["Michel Foucault", "Jacques Derrida", "Jean Baudrillard", "Roland Barthes"]', 0, 'hard'),
('Felsefe Ligi', 'Prens adlı eseriyle modern siyaset biliminin kurucusu sayılan düşünür kimdir?', '["Hobbes", "Rousseau", "Machiavelli", "Montesquieu"]', 2, 'easy'),
('Felsefe Ligi', 'Hiçlik ve Bulantı gibi eserleriyle tanınan Fransız yazar ve filozof kimdir?', '["Albert Camus", "Jean-Paul Sartre", "Simone de Beauvoir", "Maurice Merleau-Ponty"]', 1, 'medium'),
('Felsefe Ligi', 'Hangi filozof dünyayı "İsteme ve Tasarım" olarak tanımlamıştır?', '["Arthur Schopenhauer", "Friedrich Nietzsche", "Hegel", "Leibniz"]', 0, 'hard'),
('Felsefe Ligi', 'Amor Fati (Kader Sevgisi) kavramı özellikle hangi filozofla özdeşleşmiştir?', '["Seneca", "Epiktetos", "Nietzsche", "Spinoza"]', 2, 'medium'),
('Felsefe Ligi', 'Kuşkuculuğun (Skeptisizm) antik çağdaki en bilinen temsilcisi kimdir?', '["Pyrrhon", "Epiküros", "Zeno", "Thales"]', 0, 'hard'),
('Felsefe Ligi', 'Toplum Sözleşmesi adlı eseri yazan aydınlanma düşünürü kimdir?', '["Voltaire", "Diderot", "Jean-Jacques Rousseau", "John Locke"]', 2, 'easy'),
('Felsefe Ligi', 'Lev Leviathan adlı eserinde mutlak egemenliği savunan filozof kimdir?', '["Thomas Hobbes", "John Locke", "Karl Marx", "Max Weber"]', 0, 'medium'),

-- TARİH MEYDANI
('Tarih Meydanı', 'İstanbul hangi yılda fethedilmiştir?', '["1071", "1299", "1453", "1517"]', 2, 'easy'),
('Tarih Meydanı', 'Fransız İhtilali hangi yılda başlamıştır?', '["1789", "1776", "1848", "1914"]', 0, 'easy'),
('Tarih Meydanı', 'Roma İmparatorluğu ikiye ne zaman bölünmüştür?', '["M.Ö. 44", "M.S. 395", "M.S. 476", "M.S. 1453"]', 1, 'medium'),
('Tarih Meydanı', 'Birinci Dünya Savaşı hangi yıllar arasında gerçekleşmiştir?', '["1914-1918", "1939-1945", "1912-1913", "1870-1871"]', 0, 'easy'),
('Tarih Meydanı', 'Magna Carta (Büyük Şart) hangi ülkede imzalanmıştır?', '["Fransa", "İspanya", "İngiltere", "Almanya"]', 2, 'medium'),
('Tarih Meydanı', 'Osmanlı İmparatorluğu''nun kurucusu kimdir?', '["Orhan Gazi", "Osman Gazi", "I. Murad", "Ertuğrul Gazi"]', 1, 'easy'),
('Tarih Meydanı', 'Amerika kıtasını 1492 yılında keşfeden denizci kimdir?', '["Vasco da Gama", "Kristof Kolomb", "Ferdinand Macellan", "Bartolomeu Dias"]', 1, 'easy'),
('Tarih Meydanı', 'Soğuk Savaş dönemi yaklaşık olarak hangi olayla sona ermiştir?', '["Küba Füze Krizi", "Vietnam Savaşı", "Berlin Duvarı''nın Yıkılması", "Kore Savaşı"]', 2, 'medium'),
('Tarih Meydanı', 'Jül Sezar''ın öldürüldüğü tarih nedir?', '["15 Mart MÖ 44", "1 Eylül MÖ 31", "14 Şubat MÖ 27", "29 Mayıs MS 14"]', 0, 'hard'),
('Tarih Meydanı', 'Sanayi Devrimi ilk olarak hangi sektörde başlamıştır?', '["Demir-Çelik", "Kimya", "Tekstil", "Otomotiv"]', 2, 'medium'),
('Tarih Meydanı', 'Tarihteki ilk yazılı antlaşma olan Kadeş Antlaşması hangi devletler arasında imzalanmıştır?', '["Hitit - Mısır", "Sümer - Akad", "Babil - Asur", "Yunan - Pers"]', 0, 'medium'),
('Tarih Meydanı', 'Mustafa Kemal Atatürk''ün Samsun''a çıkarak Milli Mücadele''yi başlattığı tarih hangisidir?', '["23 Nisan 1920", "19 Mayıs 1919", "29 Ekim 1923", "30 Ağustos 1922"]', 1, 'easy'),
('Tarih Meydanı', 'Yüz Yıl Savaşları hangi iki ülke arasında gerçekleşmiştir?', '["İngiltere - Fransa", "Almanya - Rusya", "İspanya - Portekiz", "Osmanlı - Venedik"]', 0, 'medium'),
('Tarih Meydanı', 'Rönesans hareketleri ilk olarak hangi ülkede başlamıştır?', '["İngiltere", "Fransa", "İtalya", "Hollanda"]', 2, 'easy'),
('Tarih Meydanı', 'Pearl Harbor baskını hangi savaş sırasında gerçekleşmiştir?', '["Birinci Dünya Savaşı", "İkinci Dünya Savaşı", "Kore Savaşı", "Vietnam Savaşı"]', 1, 'easy'),
('Tarih Meydanı', 'Sovyetler Birliği (SSCB) hangi yılda resmen dağılmıştır?', '["1989", "1991", "1995", "1985"]', 1, 'medium'),
('Tarih Meydanı', 'Çin Seddi temel olarak hangi göçebe kavimlerin akınlarını durdurmak için inşa edilmiştir?', '["Hunlar ve Moğollar", "Araplar", "Slavlar", "Vikingler"]', 0, 'medium'),
('Tarih Meydanı', 'Eski Mısır krallarına verilen genel isim nedir?', '["Sezar", "Firavun", "Sultan", "Çar"]', 1, 'easy'),
('Tarih Meydanı', 'Güney Amerika''da İnka İmparatorluğu''nu yıkan İspanyol fatih kimdir?', '["Hernan Cortes", "Francisco Pizarro", "Amerigo Vespucci", "Simon Bolivar"]', 1, 'hard'),
('Tarih Meydanı', 'Osmanlı Devleti''nde matbaayı ilk getiren kişi kimdir?', '["İbrahim Müteferrika", "Katip Çelebi", "Evliya Çelebi", "Lagari Hasan Çelebi"]', 0, 'medium'),

-- EDEBİYAT DÜELLOSU
('Edebiyat Düellosu', '"İlahi Komedya" adlı eserin yazarı kimdir?', '["Homer", "Dante Alighieri", "Virgilius", "Petrarca"]', 1, 'medium'),
('Edebiyat Düellosu', 'Macbeth, Hamlet ve Othello gibi oyunların yazarı kimdir?', '["Christopher Marlowe", "Ben Jonson", "William Shakespeare", "John Milton"]', 2, 'easy'),
('Edebiyat Düellosu', '"Suç ve Ceza" romanının başkarakteri kimdir?', '["Mişkin", "Raskolnikov", "Karamazov", "Oblomov"]', 1, 'easy'),
('Edebiyat Düellosu', 'Aşağıdakilerden hangisi bir distopya romanı DEĞİLDİR?', '["1984", "Cesur Yeni Dünya", "Fahrenheit 451", "Yüzüklerin Efendisi"]', 3, 'easy'),
('Edebiyat Düellosu', '"Dönüşüm" (Die Verwandlung) adlı hikayenin yazarı kimdir?', '["Thomas Mann", "Stefan Zweig", "Franz Kafka", "Hermann Hesse"]', 2, 'medium'),
('Edebiyat Düellosu', 'Nobel Edebiyat Ödülü''nü kazanan ilk Türk yazar kimdir?', '["Yaşar Kemal", "Orhan Pamuk", "Aziz Nesin", "Sabahattin Ali"]', 1, 'easy'),
('Edebiyat Düellosu', '"Yüzyıllık Yalnızlık" romanıyla Büyülü Gerçekçilik akımını dünyaya tanıtan yazar kimdir?', '["Gabriel Garcia Marquez", "Jorge Luis Borges", "Julio Cortazar", "Isabel Allende"]', 0, 'medium'),
('Edebiyat Düellosu', '"Küçük Prens" adlı eserin yazarı Antoine de Saint-Exupéry''nin asıl mesleği neydi?', '["Öğretmen", "Doktor", "Pilot", "Mühendis"]', 2, 'medium'),
('Edebiyat Düellosu', 'Don Kişot''un sadık yardımcısının adı nedir?', '["Sancho Panza", "Dulcinea", "Rocinante", "Figaro"]', 0, 'easy'),
('Edebiyat Düellosu', '"Sefiller" (Les Misérables) romanının yazarı kimdir?', '["Emile Zola", "Gustave Flaubert", "Victor Hugo", "Honore de Balzac"]', 2, 'easy'),
('Edebiyat Düellosu', 'Hangi yazar "Yeraltından Notlar" adlı eseri yazmıştır?', '["Tolstoy", "Dostoyevski", "Turgenyev", "Çehov"]', 1, 'medium'),
('Edebiyat Düellosu', 'Tarihteki ilk yazılı destan olarak kabul edilen eser hangisidir?', '["İlyada", "Gılgamış", "Mahabharata", "Oğuz Kağan"]', 1, 'medium'),
('Edebiyat Düellosu', '"Kürk Mantolu Madonna" adlı eserin yazarı kimdir?', '["Ahmet Hamdi Tanpınar", "Sabahattin Ali", "Sait Faik Abasıyanık", "Oğuz Atay"]', 1, 'easy'),
('Edebiyat Düellosu', 'İngiliz edebiyatında "Gurur ve Önyargı" romanıyla tanınan kadın yazar kimdir?', '["Charlotte Bronte", "Virginia Woolf", "Jane Austen", "Mary Shelley"]', 2, 'medium'),
('Edebiyat Düellosu', 'James Joyce''un "Bilinçakışı" tekniğiyle yazdığı, tek bir günde geçen dev romanı hangisidir?', '["Dublinliler", "Ulysses", "Sanatçının Bir Genç Adam Olarak Portresi", "Finnegan Uyanması"]', 1, 'hard'),
('Edebiyat Düellosu', '"Büyük Birader seni izliyor" sözü hangi kitaptan alınmadır?', '["Cesur Yeni Dünya", "Hayvan Çiftliği", "Otomatik Portakal", "1984"]', 3, 'easy'),
('Edebiyat Düellosu', 'Moby Dick romanında kaptan Ahab''ın peşinden koştuğu hayvan nedir?', '["Dev bir Mürekkep Balığı", "Beyaz bir Balina", "Bir Köpekbalığı", "Bir Albatros"]', 1, 'easy'),
('Edebiyat Düellosu', 'Frankenstein romanının tam adı "Frankenstein ya da Modern..." nedir?', '["Prometheus", "Zeus", "Herkül", "Adem"]', 0, 'hard'),
('Edebiyat Düellosu', 'Türk edebiyatında ilk yerli roman kabul edilen "Taaşşuk-ı Talat ve Fitnat"ı kim yazmıştır?', '["Namık Kemal", "Şemsettin Sami", "Ahmet Mithat Efendi", "Recaizade Mahmut Ekrem"]', 1, 'hard'),
('Edebiyat Düellosu', '"Goriot Baba" ve "Vadideki Zambak" eserleriyle tanınan Fransız yazar kimdir?', '["Victor Hugo", "Stendhal", "Honore de Balzac", "Gustave Flaubert"]', 2, 'medium'),

-- SANAT ARENASI
('Sanat Arenası', 'Yıldızlı Gece (The Starry Night) tablosu kime aittir?', '["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dali"]', 1, 'easy'),
('Sanat Arenası', 'Mona Lisa tablosu şu an hangi müzede sergilenmektedir?', '["Prado Müzesi", "British Museum", "Louvre Müzesi", "Metropolitan Sanat Müzesi"]', 2, 'easy'),
('Sanat Arenası', 'Belleğin Azmi (Eriyen Saatler) tablosuyla tanınan Sürrealist ressam kimdir?', '["Rene Magritte", "Salvador Dali", "Frida Kahlo", "Joan Miro"]', 1, 'medium'),
('Sanat Arenası', 'Rönesans dönemi heykeli "Davut" (David) kimin eseridir?', '["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"]', 1, 'medium'),
('Sanat Arenası', 'Guernica tablosu hangi sanat akımının en önemli eserlerinden biridir ve kime aittir?', '["Sürrealizm / Dali", "İzlenimcilik / Monet", "Kübizm / Picasso", "Dışavurumculuk / Munch"]', 2, 'medium'),
('Sanat Arenası', '"Çığlık" (The Scream) adlı meşhur tabloyu hangi Norveçli ressam yapmıştır?', '["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Caspar David Friedrich"]', 0, 'medium'),
('Sanat Arenası', 'Leonardo da Vinci''nin "Son Akşam Yemeği" freski hangi şehirde bulunur?', '["Roma", "Floransa", "Milano", "Venedik"]', 2, 'hard'),
('Sanat Arenası', 'Hollandalı ressam Rembrandt''ın en bilinen başyapıtlarından birinin adı nedir?', '["İnci Küpeli Kız", "Gece Devriyesi", "Süt Döken Kadın", "Ayçiçekleri"]', 1, 'hard'),
('Sanat Arenası', 'Modern mimarinin öncülerinden olan ve Guggenheim Müzesi''ni tasarlayan mimar kimdir?', '["Zaha Hadid", "Le Corbusier", "Frank Lloyd Wright", "Antoni Gaudi"]', 2, 'hard'),
('Sanat Arenası', 'Barselona''daki tamamlanmamış Sagrada Familia kilisesinin mimarı kimdir?', '["Santiago Calatrava", "Antoni Gaudi", "Mies van der Rohe", "Norman Foster"]', 1, 'easy'),
('Sanat Arenası', '"Öpücük" (The Kiss) adlı altın varaklı tablonun ressamı kimdir?', '["Gustav Klimt", "Alphonse Mucha", "Egon Schiele", "Oskar Kokoschka"]', 0, 'medium'),
('Sanat Arenası', 'Pop Sanat (Pop Art) akımının en ünlü ismi olan, Marilyn Monroe portreleriyle bilinen sanatçı kimdir?', '["Roy Lichtenstein", "Jackson Pollock", "Andy Warhol", "David Hockney"]', 2, 'easy'),
('Sanat Arenası', 'Hangisi Leonardo da Vinci''nin eserlerinden biri DEĞİLDİR?', '["Mona Lisa", "Vitruvius Adamı", "Venüs''ün Doğuşu", "Son Akşam Yemeği"]', 2, 'medium'),
('Sanat Arenası', 'Sistina Şapeli''nin tavanındaki yaratılış fresklerini kim boyamıştır?', '["Sandro Botticelli", "Raphael", "Michelangelo", "Caravaggio"]', 2, 'medium'),
('Sanat Arenası', 'Kendi otoportreleri ve acılı yaşamıyla tanınan Meksikalı kadın ressam kimdir?', '["Georgia O''Keeffe", "Frida Kahlo", "Leonora Carrington", "Remedios Varo"]', 1, 'easy'),
('Sanat Arenası', 'Empresyonizm (İzlenimcilik) akımına adını veren "İzlenim: Gün Doğumu" tablosu kime aittir?', '["Edouard Manet", "Claude Monet", "Pierre-Auguste Renoir", "Edgar Degas"]', 1, 'hard'),
('Sanat Arenası', 'Nilüferler (Water Lilies) adlı devasa tablo serisi kime aittir?', '["Paul Cezanne", "Vincent van Gogh", "Claude Monet", "Paul Gauguin"]', 2, 'medium'),
('Sanat Arenası', 'Kaplumbağa Terbiyecisi adlı meşhur tablo hangi Türk ressama aittir?', '["İbrahim Çallı", "Şeker Ahmet Paşa", "Osman Hamdi Bey", "Abidin Dino"]', 2, 'easy'),
('Sanat Arenası', 'Damlama tekniğiyle (drip painting) tanınan Soyut Dışavurumcu ressam kimdir?', '["Mark Rothko", "Willem de Kooning", "Jackson Pollock", "Piet Mondrian"]', 2, 'hard'),
('Sanat Arenası', 'Temel renkler (kırmızı, mavi, sarı) ve siyah çizgilerle yaptığı soyut eserlerle bilinen Hollandalı ressam kimdir?', '["Piet Mondrian", "Wassily Kandinsky", "Kazimir Maleviç", "Joan Miro"]', 0, 'hard'),

-- BİLİM ARENASI
('Bilim', 'Görelilik Kuramı''nı (E=mc²) geliştiren bilim insanı kimdir?', '["Isaac Newton", "Niels Bohr", "Albert Einstein", "Galileo Galilei"]', 2, 'easy'),
('Bilim', 'DNA''nın çift sarmal yapısını çözen bilim insanları kimlerdir?', '["Watson & Crick", "Pasteur & Koch", "Curie & Becquerel", "Darwin & Wallace"]', 0, 'medium'),
('Bilim', 'Dünya''nın Güneş etrafında döndüğünü savunan ve bu yüzden engizisyonda yargılanan İtalyan astronom kimdir?', '["Kopernik", "Kepler", "Galileo", "Ptolemaios"]', 2, 'easy'),
('Bilim', 'Evrimin mekanizması olan "Doğal Seçilim" fikrini öne süren kitabın adı nedir?', '["Türlerin Kökeni", "Principia", "Gen Bencildir", "Kör Saatçi"]', 0, 'medium'),
('Bilim', 'Periyodik tabloyu oluşturan Rus kimyager kimdir?', '["Dmitri Mendeleyev", "Antoine Lavoisier", "Marie Curie", "Louis Pasteur"]', 0, 'medium'),
('Bilim', 'Radyoaktiviteyi keşfeden ve iki farklı alanda Nobel ödülü alan bilim insanı kimdir?', '["Rosalind Franklin", "Marie Curie", "Lise Meitner", "Ada Lovelace"]', 1, 'easy'),
('Bilim', 'Evrenin genişlediğini keşfeden astronom kimdir?', '["Carl Sagan", "Stephen Hawking", "Edwin Hubble", "Johannes Kepler"]', 2, 'medium'),
('Bilim', 'Kara deliklerin radyasyon yaydığını kanıtlayan fizikçi kimdir?', '["Albert Einstein", "Richard Feynman", "Stephen Hawking", "Kip Thorne"]', 2, 'medium'),
('Bilim', 'Yerçekimi kanunlarını formüle eden ve "Principia" eserini yazan kişi kimdir?', '["Isaac Newton", "Albert Einstein", "Max Planck", "Johannes Kepler"]', 0, 'easy'),
('Bilim', 'İlk antibiyotik olan Penisilin''i kim keşfetmiştir?', '["Louis Pasteur", "Alexander Fleming", "Jonas Salk", "Edward Jenner"]', 1, 'easy'),
('Bilim', 'Kuantum mekaniğinde kedisiyle bilinen düşünce deneyinin sahibi kimdir?', '["Werner Heisenberg", "Max Planck", "Erwin Schrödinger", "Niels Bohr"]', 2, 'easy'),
('Bilim', 'Hangi gezegen Güneş sistemindeki en büyük gezegendir?', '["Dünya", "Satürn", "Mars", "Jüpiter"]', 3, 'easy'),
('Bilim', 'İzafiyet teorisine göre ışık hızına yaklaşıldıkça zaman nasıl değişir?', '["Hızlanır", "Yavaşlar", "Durur", "Geriye akar"]', 1, 'medium'),
('Bilim', 'Elektromanyetik dalgaların varlığını teorik olarak kanıtlayan İskoç fizikçi kimdir?', '["James Clerk Maxwell", "Michael Faraday", "Nikola Tesla", "Heinrich Hertz"]', 0, 'hard'),
('Bilim', 'Büyük Hadron Çarpıştırıcısı (LHC) hangi bilimsel araştırma merkezinde bulunmaktadır?', '["NASA", "CERN", "ESA", "Fermilab"]', 1, 'easy'),
('Bilim', 'Atomun çekirdeğini ilk kez tanımlayan deney (Altın Folyo) kime aittir?', '["J.J. Thomson", "Ernest Rutherford", "Niels Bohr", "John Dalton"]', 1, 'hard'),
('Bilim', 'İlk bilgisayar programcısı olarak kabul edilen kişi kimdir?', '["Alan Turing", "Charles Babbage", "Ada Lovelace", "Grace Hopper"]', 2, 'medium'),
('Bilim', 'Turing testi neyi ölçmek için tasarlanmıştır?', '["Bir makinenin hızını", "Bir makinenin insan gibi düşünüp düşünemediğini", "İnternet bağlantısını", "Şifreleme gücünü"]', 1, 'easy'),
('Bilim', 'Işığın hem dalga hem de parçacık özelliği gösterdiğini kanıtlayan deneyin adı nedir?', '["Çift Yarık Deneyi", "Michelson-Morley Deneyi", "Schrödinger Deneyi", "Foucault Sarkacı"]', 0, 'medium'),
('Bilim', 'Oksijeni keşfeden ve modern kimyanın babası sayılan, Fransız İhtilalinde giyotinle idam edilen bilim insanı kimdir?', '["Antoine Lavoisier", "Dmitri Mendeleyev", "Amedeo Avogadro", "John Dalton"]', 0, 'hard');
